### ISSUE TITLE
Change preferred labels of micro-plastic category types

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/H01#3]
see https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19

**Comment by gwemon** [comment]
Changes implemented to the following concepts:
H0100002	fragments	Irregularly-shaped plastic micro-litter particles with broken off edges that may be rounded or angular.
H0100003	pellets	Micro-litter particles from industrial origin only. In comparison with granules, pellets are usually flat on one side, rough surface and irregular, round shapes. Normally bigger in size.
H0100004	filaments	Slender thread-like micro-litter particles.
H0100005	films	Micro-litter particles derived from plastic sheets or thin plastic films.
H0100006	foams	Any kind of micro-litter particle made of plastic foam, including styrofoam.

**Comment by gwemon** [comment]
Awaiting decision on H0100001	microplastic items	A generic term for any kind of micro-litter item made of any kind of plastic material. See https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19#issuecomment-1168477338

**Comment by mmolinajack** [comment]
Hi @gwemon,
following your suggestion in https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19 , we would like to create the term "not specified" defined as "a generic morphology not specified in source data..." and avoid creating "other morphologies" in order to stimulate the request of additional morphologies if needed. Do you agree?
If so, for us is ok to proceed.
Thanks!

**Comment by gwemon** [comment]
So I will deprecate http://vocab.nerc.ac.uk/collection/H01/current/H0100001/ and create a new concept in H01 for "not specified".

**Comment by gwemon** [comment]
The new term will need to be mapped to http://vocab.nerc.ac.uk/collection/P01/current/MLITTYPW/ and http://vocab.nerc.ac.uk/collection/P01/current/MLITTYPS/ 
Is that correct @mmolinajack ? And are there any other changes you requested that I may have forgotten?

**Comment by mmolinajack** [comment]
Yes, correct. I think all the needed updates are done, thanks!. Just a question: I have seen that the related terms in http://vocab.nerc.ac.uk/collection/P01/current/MLITTYPW/ still contain deprecated terms as:

H01:H0100007 | non-plastic man-made micro-particles (e.g. glass, metal, tar)
Will this be updated?
Thanks

**Comment by gwemon** [comment]
> Yes, correct. I think all the needed updates are done, thanks!. Just a question: I have seen that the related terms in http://vocab.nerc.ac.uk/collection/P01/current/MLITTYPW/ still contain deprecated terms as:
> 
> H01:H0100007 | non-plastic man-made micro-particles (e.g. glass, metal, tar) Will this be updated? Thanks

Yes I forgot to update the mappings. I'll remove it.

**Comment by mmolinajack** [comment]
Super! thanks

**Comment by mmolinajack** [comment]
Hi @gwemon, 
we have received the input that we still have references to the "plastic" in the H01 vocabulary so we have decided to review it and if possible face the pending issues.
We propose to modify the following definitions:
				
Modify H0100001 as follows:					
Micro-litter items: http://vocab.nerc.ac.uk/collection/H01/current/H0100001/	SDN:H01::H0100001
Proposed definition: A generic term for any kind of micro-litter item where its precise morphology was not recorded	
					
 Modify H0100006 as follows:					
Foams: http://vocab.nerc.ac.uk/collection/H01/current/H0100006/	SDN:H01::H0100006	
Proposed definition: Flexible micro-litter particles in which material cells are all or partly intercommunicating (adapted from ISO definition for foam https://www.iso.org/obp/ui/#iso:std:iso:tr:20342:-7:ed-1:v1:en)
					
 Modify H0100002 as follows:					
Fragments: http://vocab.nerc.ac.uk/collection/H01/current/H0100002/	SDN:H01::H0100002	
Proposed definition: Irregularly-shaped micro-litter particles with broken off edges that may be rounded or angular.	

What do you think?
Thanks,
Eugenia and Matteo

**Comment by mmolinajack** [comment]
Hi @gwemon,
what do you think of our proposal? 
In addition, this would allow to finish the implementation of #5 which we have seen that it is open as well.
Thanks,
Eugenia and Matteo


@mattevi78

**Comment by gwemon** [comment]
Apologies for the delay in responding @mmolinajack @mattevi78. 
I think that the following modifications are fine:

Modify H0100006 as follows:
Foams: http://vocab.nerc.ac.uk/collection/H01/current/H0100006/ SDN:H01::H0100006
Proposed definition: Flexible micro-litter particles in which material cells are all or partly intercommunicating (adapted from ISO definition for foam [https://www.iso.org/obp/ui/#iso:std:iso🇹🇷20342:-7:ed-1:v1:en](https://www.iso.org/obp/ui/#iso:std:iso:tr:20342:-7:ed-1:v1:en))

Modify H0100002 as follows:
Fragments: http://vocab.nerc.ac.uk/collection/H01/current/H0100002/ SDN:H01::H0100002
Proposed definition: Irregularly-shaped micro-litter particles with broken off edges that may be rounded or angular.

But I am wondering about the proposed changes to Modify H0100001 as follows:
Micro-litter items: http://vocab.nerc.ac.uk/collection/H01/current/H0100001/ SDN:H01::H0100001
Proposed definition: A generic term for any kind of micro-litter item where its precise morphology was not recorded

If H01 is a vocabulary about the morphological type of the particles then do you need H0100001 at all? Should it not be simply deprecated? and replaced by a new term for "not specified"? Or we could modify H0100001 to become "Undefined type".

**Comment by mmolinajack** [comment]
Hi Gwen,
thanks. Regarding:

> But I am wondering about the proposed changes to Modify H0100001 as follows:
Micro-litter items: http://vocab.nerc.ac.uk/collection/H01/current/H0100001/ SDN:H01::H0100001
Proposed definition: A generic term for any kind of micro-litter item where its precise morphology was not recorded

>If H01 is a vocabulary about the morphological type of the particles then do you need H0100001 at all? Should it not be simply deprecated? and replaced by a new term for "not specified"? Or we could modify H0100001 to become "Undefined type".

Deprecate that term would have lots of consecuences on the existing data as it is often used. We would propose to maintain the existing term defined as follows:
A generic term for any kind of micro-litter **particle** where its precise morphology was not recorded **or it is not specified**

Would you agree?

Eugenia and @mattevi78

**Comment by gwemon** [comment]
@mmolinajack and @mattevi78 I understand. In that case I'd suggest adopting "Undefined type" or "Undefined micro-litter type" (I think the latter is probably better) as the preflabel with your definition adapted to "A generic term for any kind of micro-litter particle whose morphological type is not specified.".
Would that work?

**Comment by mmolinajack** [comment]
We agree with "Undefined micro-litter type"
Thanks!

**Comment by gwemon** [comment]
@mmolinajack and @mattevi78 Just to make you aware that the only problem with the approach we are taking (of not deprecating) is that people would have used H0100001 up until now to refer to "undefined microplastic items" rather than "Undefined micro-litter items" so by changing (broadening) the meaning of H0100001 the information about the fact that those items were plastic will be lost. Alternatively if we deprecate H0100001 and create a new one for "Undefined micro-litter items" the information is preserved.

**Comment by mmolinajack** [comment]
Hi @gwemon,
you are right and probably this would have been the way to proceed with the other terms in the list. Anyway, we agree with the deprecation of the H0100001 and the creation a new one for "Undefined micro-litter items" to preserve the information.
Thanks

**Comment by mmolinajack** [comment]
Hi @gwemon,
any chance that this vocabulary can be updated on the short term with the modifications we agreed?
Thanks!
Eugenia

**Comment by gwemon** [comment]
Changes made and queued for publication on the NVS. New term H0100010 created for Undefined micro-litter items. Decided not to set up a "replaced by" link set up because H0100001 and H0100010 are not equivalent and the substitution requires manual intervention and mapping to a term from http://vocab.nerc.ac.uk/collection/H05/current/.
@mmolinajack Apologies for forgetting about what I think was the last of the changes you requested but please could you check tomorrow (when changes come live on the NVS) that all the changes you wanted are in place?

**Comment by mmolinajack** [comment]
Yes, I will. Thanks!

**Comment by mmolinajack** [comment]
Hi @gwemon, the changes are fine, thanks. 
The only thing is that the one related to the foams is missing: 
>

>  Modify H0100006 as follows:
> Foams: http://vocab.nerc.ac.uk/collection/H01/current/H0100006/ SDN:H01::H0100006
> Proposed definition: Flexible micro-litter particles in which material cells are all or partly intercommunicating (adapted from ISO definition for foam [https://www.iso.org/obp/ui/#iso:std:iso🇹🇷20342:-7:ed-1:v1:en](https://www.iso.org/obp/ui/#iso:std:iso:tr:20342:-7:ed-1:v1:en))
> 
Thanks!
Eugenia

**Comment by gwemon** [comment]
Thank you @mmolinajack I have updated our records and it's been queued for tomorrow's publication.

**Comment by mmolinajack** [comment]
Hi @gwemon ,
thanks! I have realized that fragments still contains "plastic" in the definition:
Irregularly-shaped **plastic** micro-litter particles with broken off edges that may be rounded or angular.
Could you please update the definition pulling out "plastic" from it?

**Comment by mmolinajack** [comment]
In the meantime I have found the definition of **film** in the ISO vocabulary:
https://www.iso.org/obp/ui/#iso:std:iso:5148:ed-1:v1:en:term:3.1.
What do you think of changing [H0100005](http://vocab.nerc.ac.uk/collection/H01/current/H0100005/) as well like:
Thin planar micro-litter particles of arbitrarily limited maximum thickness, in which the thickness is very small compared to the length and width (adapted from ISO definition for film https://www.iso.org/obp/ui/#iso:std:iso:5148:ed-1:v1:en:term:3.1).
In this way, we would clean the whole vocabulary from the word "plastic".
Does this make sense?

**Comment by mmolinajack** [comment]
Hi @gwemon,
when you have time, please don't forget this request.
> Hi @gwemon , thanks! I have realized that fragments still contains "plastic" in the definition: Irregularly-shaped **plastic** micro-litter particles with broken off edges that may be rounded or angular. Could you please update the definition pulling out "plastic" from it?
Thanks,
Eugenia

**Comment by gwemon** [comment]
Done @mmolinajack . There are also mentions of "plastic" in http://vocab.nerc.ac.uk/collection/H01/current/H0100005/ 
Is that also something you want to remove? If so, could you suggest another description for "films"?
Many thanks.

**Comment by mmolinajack** [comment]
Hi @gwemon, thanks.
Last week we had some exchange with the Spanish colleagues regarding the films. 
We had found a good definition for films from ISO: Thin planar micro-litter particles of arbitrarily limited maximum thickness, in which the thickness is very small compared to the length and width (adapted from ISO definition for film https://www.iso.org/obp/ui/#iso:std:iso:5148:ed-1:v1:en:term:3.1).
However, the Spanish colleagues from IEO said that with this definition, paint pieces could be classified both as fragments and as films and this is true. 
They gave me this 2 references that might be useful:

- Isobe A., Buenaventura N.T., Chastain S., Chavanich S., Cózar A., DeLorenzo M., Hagmann P., Hinata H., Kozlovskii N., Lusher A.L., Martí E., Michida Y., Mu J., Ohno M., Potter G, Ross P.S., Sagawa N., Shim W.J., Song Y.K., Takada H, Tokai T., Torii T., Uchida K., Vassillenko K., Viyakarn V., Zhang W. 2019. An interlaboratory comparison exercise for the determination of microplastics in standard sample bottles. Marine Pollution Bulletin, Volume 146, https://doi.org/10.1016/j.marpolbul.2019.07.033.

- Lusher AL, Bråte ILN, Munno K, Hurley RR, Welden NA. Is It or Isn’t It: The Importance of Visual Classification in Microplastic Characterization. Applied Spectroscopy. 2020;74(9):1139-1153. doi:[10.1177/0003702820930733](https://doi.org/10.1177/0003702820930733)

Lusher et al, defines films similarly to the ISO definition. Instead, Isobe et al, adds that films are more flexible than fragments that tend to break easily.

As we are not experts, for the time being, we have decided to clean the definition from the "plastic" and leave it as: Micro-litter particles derived from sheets or thin films. 
We know that this definition is not very good but we don't want to make changes till we have a good proposal.
We hope you agree.
Thanks,
Eugenia and @mattevi78

**Comment by mmolinajack** [comment]
Hi @gwemon, did you have time to look at our proposal regarding the films from the previous message:

> clean the definition from the "plastic" and leave it as: Micro-litter particles derived from sheets or thin films.

Do you agree?
For us is ok to proceed.
Thanks,
Eugenia and @mattevi78

**Comment by gwemon** [comment]
Sorry was on leave. Done. It will be live tomorrow.

**Comment by gwemon** [comment]
@mmolinajack @mattevi78 what should paint fragments be classified as? Fragments? Is that correct? if so then we might want to make it explicit? Could we not go for a definition that includes Isobe et al statement? e.g.

"Thin planar micro-litter particles of arbitrarily limited maximum thickness, in which the thickness is very small compared to the length and width (adapted from ISO definition for film https://www.iso.org/obp/ui/#iso:std:iso:5148:ed-1:v1:en:term:3.1). In the micro-litter nomenclature, particles of type "films" are more flexible than particles of type "fragments" with the latter tending to break easily (Isobe et al 2019)."

This can be debated and refined later but I think it has the merit to being explicit about the distinction. If need be where paint "fragments" go (films or fragments) could also be  specified as an example if you think that could be helpful to the users.

**Comment by mmolinajack** [comment]
Hi @gwemon,
sorry, somehow we skipped your reply. We like your proposal very much. 
Please, go ahead, once the change has been made, we will inform the TGML about the changes in this vocabulary.
Thanks,
Eugenia and @mattevi78

**Comment by gwemon** [comment]
Change applied @mmolinajack and @mattevi78. It will be live tomorrow.

**Comment by mmolinajack** [comment]
Thanks!

**Comment by gwemon** [comment]
I think I forgot to close this issue. As far as I cansee all the updates agreed upon have been addressed.
