### ISSUE TITLE
Change name of collection to reflect focus on morphology of micro-litter particles

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/H01#5]
The H01 collection was effectively defining a shapes but also specifying plastic and non-plastic materials. Decision of review (see https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19) was to remove information about plastic/non-plastic and only have terms that relates to morphological types. 
So the proposal is to change the name of the H01 collection from:
EMODnet micro-litter types
to:
EMODnet micro-litter morphological types
with description: "Controlled vocabulary defining the terms that may be used for micro-litter particle morphological types (e.g. pellets, fragments, etc.) in the EMODnet Chemistry data reporting system."

Short name: microlitter_shapes

@mmolinajack I'll implement these changes once I have received your thumb up.

**Comment by mmolinajack** [comment]
Hi @gwemon,
we agree with your proposal:

> So the proposal is to change the name of the H01 collection from:
EMODnet micro-litter types
to:
EMODnet micro-litter morphological types
with description: "Controlled vocabulary defining the terms that may be used for micro-litter particle morphological types (e.g. pellets, fragments, etc.) in the EMODnet Chemistry data reporting system."

Instead, regarding the short name, we would propose: microlitter_structure. The term you proposed is already used for the H02 vocabulary.

For us, the implementation of the changes can be done. Thanks!

**Comment by gwemon** [comment]
@mmolinajack On reflection, I am concerned about how the propose change to H01 name and description bring the definition of H01 and H02 confusingly close to one another. I think that it is okay to remove all reference to "plastic" or any other material from the concept definition but still but keep the scope of the vocabulary to the definition of "types". So my proposal would be:
Keep name of H01 as: "EMODnet micro-litter types"
Short_name as: "Microlitter_type"
Definition can be made more explicit as follows: "Controlled vocabulary defining the terms that may be used for micro-litter particle types in the EMODnet Chemistry data reporting system. The categories reflect only types based on morphological criteria (e.g. pellets, fragments, etc.) and all reference to the material they were made of was removed from this vocabulary as agreed in https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19."

I do believe that the concepts:
fragments
pellets
filaments
films
foams
granules
fit that definition. Would you agree?

**Comment by mmolinajack** [comment]
Yes, we agree!
Thanks,
Eugenia and @mattevi78

**Comment by gwemon** [comment]
Change to the description of the H01 collection has been made and queued for publication on the NVS.

**Comment by gwemon** [comment]
Changes to the description of H01 implemented: http://vocab.nerc.ac.uk/collection/H01/current/
Name renamed unchanged as agreed.
